ContactsManagement/Controllers/ContactController.cs
using ContactsManagement.Models;
using ContactsManagement.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ContactsManagement.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository _contactRepository;

        public ContactController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }
        public IActionResult Index()
        {
            var contacts = _contactRepository.GetAll();

            return View(contacts);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(long id)
        {
            ContactModel contact = _contactRepository.GetContact(id)!;
            return View(contact);
        }

        public IActionResult ConfirmDelete(long id)
        {
            ContactModel contact = _contactRepository.GetContact(id)!;
            return View(contact);
        }

        [HttpPost]
        public IActionResult Create(ContactModel contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contactRepository.Create(contact);
                    TempData["SuccessMessage"] = "Contact successfully added.";
                    return RedirectToAction("Index");
                }

                return View(contact);
            }
            catch (System.Exception error)
            {
                TempData["ErrorMessage"] = $"Oops, we were unable to add your contact, please try again. {error.Message}";
                return RedirectToAction("Index");   
            }    
        }

        [HttpPost]
        public IActionResult Edit(ContactModel contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contactRepository.Update(contact);
                    TempData["SuccessMessage"] = "Contact successfully edited.";
                    return RedirectToAction("Index");
                }
                return View(contact);
            }
            catch (System.Exception error)
            {
                TempData["ErrorMessage"] = $"Oops, we were unable to edit your contact, please try again. {error.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Delete(long id)
        {
            try
            {
                bool deleted = _contactRepository.Delete(id);

                if (deleted)
                {
                    TempData["SuccessMessage"] = "Contact successfully deleted!";
                }
                else
                {
                    TempData["ErrorMessage"] = $"Oops, we were unable to delete your contact!";
                }

                return RedirectToAction("Index");
            }
            catch (System.Exception error)
            {
                TempData["ErrorMessage"] = $"Oops, we were unable to delete your contact, please try again. {error.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ContactsManagement/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ContactsManagement.Models;
using ContactsManagement.Repositories;

namespace ContactsManagement.Controllers
{
	public class UserController : Controller
	{
		private readonly IUserRepository _userRepository;

		public UserController(IUserRepository userRepository)
		{
			_userRepository = userRepository;
		}

		public IActionResult Index()
		{
			var users = _userRepository.GetAll();

			return View(users);
		}

		public IActionResult Create()
		{
			return View();
		}

		public IActionResult Edit(long id)
		{
			UserModel user = _userRepository.GetUser(id);
			return View(user);
		}

		public IActionResult DeleteConfirmed(long id)
		{
			UserModel user = _userRepository.GetUser(id);
			return View(user);
		}

		[HttpPost]
		public IActionResult Create(UserModel user)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_userRepository.Create(user);
					TempData["SuccessMessage"] = "User successfully added.";
					return RedirectToAction("Index");
				}

				return View(user);
			}
			catch (System.Exception error)
			{
				TempData["ErrorMessage"] = $"Oops, we were unable to add your user, please try again. {error.Message}";
				return RedirectToAction("Index");
			}
		}

		[HttpPost]
		public IActionResult Edit(UserWithoutPasswordModel userWP)
		{
			try
			{
				UserModel user = null!;

				if (ModelState.IsValid)
				{
					user = new UserModel()
					{
						Id = userWP.Id,
						Name = userWP.Name,
						Login = userWP.Login,
						Email = userWP.Email,
						UserType = userWP.UserType
					};

					user = _userRepository.Update(user);
					TempData["SuccessMessage"] = "User successfully edited.";
					return RedirectToAction("Index");
				}

				return View(user);
			}
			catch (Exception error)
			{
				TempData["ErrorMessage"] = $"Oops, we were unable to edit your user, please try again. {error.Message}";
				return RedirectToAction("Index");
			}
		}

		[HttpPost, ActionName("Delete")]
		public IActionResult Delete(long id)
		{

			try
			{
				bool deleted = _userRepository.Delete(id);

				if (deleted)
				{
					TempData["SuccessMessage"] = "User successfully deleted!";
				}
				else
				{
					TempData["ErrorMessage"] = $"Oops, we were unable to delete your user!";
				}
				return RedirectToAction("Index");
			}
			catch (Exception error)
			{
				TempData["ErrorMessage"] = $"Oops, we were unable to delete your user, please try again. {error.Message}";
				return RedirectToAction("Index");
			}
		}

	}

}

ContactsManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contacts Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact"
                                asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Contacts Control
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ContactsManagement/Views/Shared/_LoggedOutLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.4/datatables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contacts Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Contacts Management
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>